-- Account: MMVDVTK-DW81715 | Setup user: MCHAYES89
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE REFINERY;
USE SCHEMA PUBLIC;

-- OAuth uses a regular application role with read access to your existing data.
CREATE ROLE IF NOT EXISTS CLOUDFLARE_OS_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE CLOUDFLARE_OS_ROLE;
GRANT USAGE ON DATABASE REFINERY TO ROLE CLOUDFLARE_OS_ROLE;
GRANT USAGE ON SCHEMA REFINERY.PUBLIC TO ROLE CLOUDFLARE_OS_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA REFINERY.PUBLIC TO ROLE CLOUDFLARE_OS_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA REFINERY.PUBLIC TO ROLE CLOUDFLARE_OS_ROLE;
GRANT ROLE CLOUDFLARE_OS_ROLE TO USER MCHAYES89;

CREATE SECURITY INTEGRATION IF NOT EXISTS CLOUDFLARE_OS_SNOWFLAKE_OAUTH
  TYPE = OAUTH
  ENABLED = TRUE
  OAUTH_CLIENT = CUSTOM
  OAUTH_CLIENT_TYPE = 'CONFIDENTIAL'
  OAUTH_REDIRECT_URI = 'https://hellgate-os-router.mchayes89.workers.dev/gatekeeper/snowflake/oauth'
  OAUTH_ENFORCE_PKCE = TRUE
  OAUTH_ISSUE_REFRESH_TOKENS = TRUE
  OAUTH_REFRESH_TOKEN_VALIDITY = 86400;

GRANT USAGE ON INTEGRATION CLOUDFLARE_OS_SNOWFLAKE_OAUTH TO ROLE CLOUDFLARE_OS_ROLE;

-- Copy the final JSON result into .secrets/hellgate-os-gatekeeper-snowflake.json.
WITH oauth AS (
  SELECT PARSE_JSON(SYSTEM$SHOW_OAUTH_CLIENT_SECRETS('CLOUDFLARE_OS_SNOWFLAKE_OAUTH')) AS settings
)
SELECT OBJECT_CONSTRUCT(
  'SNOWFLAKE_ACCOUNT', 'MMVDVTK-DW81715',
  'SNOWFLAKE_ROLE', 'CLOUDFLARE_OS_ROLE',
  'CLIENT_ID', COALESCE(settings:OAUTH_CLIENT_ID::STRING, settings:oauth_client_id::STRING),
  'CLIENT_SECRET', COALESCE(settings:OAUTH_CLIENT_SECRET::STRING, settings:oauth_client_secret::STRING)
) AS CREDENTIALS_JSON
FROM oauth;
